### ISSUE TITLE
Generics generate impractical entities

### ISSUE THREAD

**Issue by GrantHoffman** [DogusTeknoloji/cs-to-ts#5]
When translating C# generic new(), this will generate conditions impossible to satisfy

    export class Company<TAddress extends Address & { new(): TAddress }> extends 
        BaseEntity<number> {
             Income: number;
             Name: string;
             EmployeeCount: number;
             Address: Array<TAddress>;
      }

This is making the claim that TAddress is and Address and a constructor which returns TAddress.  Constructors don't return values.  

Additionally, if you were to declare that TAddress has a parameterless constructor, you the generator should generate the Address entity compatible with the Company, but if you were to try to create a new Company<Address>().   This will fail.

**Comment by umutozel** [comment]
Sorry for the late reply.

You're right, because we don't have a type system we can't easily add parameterless ctor constraint. Example you provided is my mistake, I believe I didn't think it through.

I'm removing new() constraint for now.

**Comment by umutozel** [comment]
Published 1.3.12 NuGet.
